# coding: utf-8

"""
    spitfire API

    spitfire API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.subscriptionresource_api import SubscriptionresourceApi


class TestSubscriptionresourceApi(unittest.TestCase):
    """ SubscriptionresourceApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.subscriptionresource_api.SubscriptionresourceApi()

    def tearDown(self):
        pass

    def test_create_subscription_using_post(self):
        """
        Test case for create_subscription_using_post

        createSubscription
        """
        pass

    def test_delete_subscription_using_delete(self):
        """
        Test case for delete_subscription_using_delete

        deleteSubscription
        """
        pass

    def test_get_all_subscriptions_using_get(self):
        """
        Test case for get_all_subscriptions_using_get

        getAllSubscriptions
        """
        pass

    def test_get_subscription_using_get(self):
        """
        Test case for get_subscription_using_get

        getSubscription
        """
        pass

    def test_update_subscription_using_put(self):
        """
        Test case for update_subscription_using_put

        updateSubscription
        """
        pass


if __name__ == '__main__':
    unittest.main()
