# coding: utf-8

"""
    spitfire API

    spitfire API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.activitymessageresource_api import ActivitymessageresourceApi


class TestActivitymessageresourceApi(unittest.TestCase):
    """ ActivitymessageresourceApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.activitymessageresource_api.ActivitymessageresourceApi()

    def tearDown(self):
        pass

    def test_create_activity_message_using_post(self):
        """
        Test case for create_activity_message_using_post

        createActivityMessage
        """
        pass

    def test_delete_activity_message_using_delete(self):
        """
        Test case for delete_activity_message_using_delete

        deleteActivityMessage
        """
        pass

    def test_get_activity_message_using_get(self):
        """
        Test case for get_activity_message_using_get

        getActivityMessage
        """
        pass

    def test_get_all_activity_messages_using_get(self):
        """
        Test case for get_all_activity_messages_using_get

        getAllActivityMessages
        """
        pass

    def test_search_activity_messages_using_get(self):
        """
        Test case for search_activity_messages_using_get

        searchActivityMessages
        """
        pass

    def test_update_activity_message_using_put(self):
        """
        Test case for update_activity_message_using_put

        updateActivityMessage
        """
        pass


if __name__ == '__main__':
    unittest.main()
