# coding: utf-8

"""
    spitfire API

    spitfire API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Subscription(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, customer=None, id=None, plan=None, subscription_key=None):
        """
        Subscription - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'customer': 'Customer',
            'id': 'int',
            'plan': 'Plan',
            'subscription_key': 'str'
        }

        self.attribute_map = {
            'customer': 'customer',
            'id': 'id',
            'plan': 'plan',
            'subscription_key': 'subscriptionKey'
        }

        self._customer = customer
        self._id = id
        self._plan = plan
        self._subscription_key = subscription_key


    @property
    def customer(self):
        """
        Gets the customer of this Subscription.


        :return: The customer of this Subscription.
        :rtype: Customer
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """
        Sets the customer of this Subscription.


        :param customer: The customer of this Subscription.
        :type: Customer
        """

        self._customer = customer

    @property
    def id(self):
        """
        Gets the id of this Subscription.


        :return: The id of this Subscription.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Subscription.


        :param id: The id of this Subscription.
        :type: int
        """

        self._id = id

    @property
    def plan(self):
        """
        Gets the plan of this Subscription.


        :return: The plan of this Subscription.
        :rtype: Plan
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """
        Sets the plan of this Subscription.


        :param plan: The plan of this Subscription.
        :type: Plan
        """

        self._plan = plan

    @property
    def subscription_key(self):
        """
        Gets the subscription_key of this Subscription.


        :return: The subscription_key of this Subscription.
        :rtype: str
        """
        return self._subscription_key

    @subscription_key.setter
    def subscription_key(self, subscription_key):
        """
        Sets the subscription_key of this Subscription.


        :param subscription_key: The subscription_key of this Subscription.
        :type: str
        """

        self._subscription_key = subscription_key

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
